"""create daily water summary table

Revision ID: 55703cea55b7
Revises: 1234567890ab
Create Date: 2025-05-19 12:44:36.983767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55703cea55b7'
down_revision: Union[str, None] = '1234567890ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_food_entries_food_name', table_name='food_entries')
    op.drop_index('ix_food_entries_id', table_name='food_entries')
    op.drop_table('food_entries')
    op.drop_index('ix_daily_nutrient_summaries_id', table_name='daily_nutrient_summaries')
    op.drop_table('daily_nutrient_summaries')
    op.drop_index('ix_food_intakes_id', table_name='food_intakes')
    op.drop_table('food_intakes')
    op.drop_table('water_reminder')
    op.add_column('daily_water_summary', sa.Column('total_ml', sa.Integer(), nullable=True))
    op.alter_column('daily_water_summary', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_daily_water_summary_summary_id'), 'daily_water_summary', ['summary_id'], unique=False)
    op.drop_constraint('daily_water_summary_user_id_fkey', 'daily_water_summary', type_='foreignkey')
    op.create_foreign_key(None, 'daily_water_summary', 'users', ['user_id'], ['id'])
    op.drop_column('daily_water_summary', 'remaining_ml')
    op.drop_column('daily_water_summary', 'status')
    op.drop_column('daily_water_summary', 'total_intake_ml')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'foto_profil')
    op.drop_index('idx_water_intake_user_id', table_name='water_intake')
    op.create_index(op.f('ix_water_intake_intake_id'), 'water_intake', ['intake_id'], unique=False)
    op.drop_constraint('water_intake_summary_id_fkey', 'water_intake', type_='foreignkey')
    op.drop_constraint('water_intake_user_id_fkey', 'water_intake', type_='foreignkey')
    op.create_foreign_key(None, 'water_intake', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'water_intake', 'daily_water_summary', ['summary_id'], ['summary_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'water_intake', type_='foreignkey')
    op.drop_constraint(None, 'water_intake', type_='foreignkey')
    op.create_foreign_key('water_intake_user_id_fkey', 'water_intake', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('water_intake_summary_id_fkey', 'water_intake', 'daily_water_summary', ['summary_id'], ['summary_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_water_intake_intake_id'), table_name='water_intake')
    op.create_index('idx_water_intake_user_id', 'water_intake', ['user_id'], unique=False)
    op.add_column('users', sa.Column('foto_profil', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('daily_water_summary', sa.Column('total_intake_ml', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('daily_water_summary', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('daily_water_summary', sa.Column('remaining_ml', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'daily_water_summary', type_='foreignkey')
    op.create_foreign_key('daily_water_summary_user_id_fkey', 'daily_water_summary', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_daily_water_summary_summary_id'), table_name='daily_water_summary')
    op.alter_column('daily_water_summary', 'date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('daily_water_summary', 'total_ml')
    op.create_table('water_reminder',
    sa.Column('reminder_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reminder_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['Pending'::character varying, 'Done'::character varying]::text[])", name='water_reminder_status_check'),
    sa.ForeignKeyConstraint(['summary_id'], ['daily_water_summary.summary_id'], name='water_reminder_summary_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reminder_id', name='water_reminder_pkey')
    )
    op.create_table('food_intakes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('protein', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount_grams', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='food_intakes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='food_intakes_pkey')
    )
    op.create_index('ix_food_intakes_id', 'food_intakes', ['id'], unique=False)
    op.create_table('daily_nutrient_summaries',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('daily_nutrient_summaries_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('protein', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fiber', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sugar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sodium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='daily_nutrient_summaries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_nutrient_summaries_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_daily_nutrient_summaries_id', 'daily_nutrient_summaries', ['id'], unique=False)
    op.create_table('food_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('daily_summary_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('food_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('serving_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('serving_unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('protein', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fiber', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sugar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sodium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('added_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['daily_summary_id'], ['daily_nutrient_summaries.id'], name='food_entries_daily_summary_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='food_entries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='food_entries_pkey')
    )
    op.create_index('ix_food_entries_id', 'food_entries', ['id'], unique=False)
    op.create_index('ix_food_entries_food_name', 'food_entries', ['food_name'], unique=False)
    # ### end Alembic commands ###
